name: versions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: expr $(cat version.html) + 1 > version.html
      - run: git config --global user.name "py660"
      - run: git config --global user.email "93660666+py660@users.noreply.github.com"
      - run: git add version.html
      - run: git commit -m "bump version"
      - run: git push
