name: versions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2.3.4
      - run: expr $(cat version.html) + 1 > version.html
      - run: ls
